baseURL = "https://danielsagala.netlify.app"
languageCode = "id"
theme = "adritian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "Tentang"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Kontak"
  URL = "#contact"
  weight = 6

  [[menu.footer]]
  name = "Tentang"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Kontak"
  URL = "#contact"
  weight = 4


[params]

  sections = ["showcase", "about", "education", "experience", "client-and-work", "testimonial", "contact", "newsletter"]

  homepageExperienceCount = 6

  [params.google_analytics]
      code = "UA-XXXXX-Y"
      enabled = false
  [params.google_tag_manager]
      code = "GTM-XXXXX"
      enabled = false
  
  [params.logo]
    text1 = "Daniel"
    text2 = "Sagala"

